sudo: required
services:
  - docker
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7" 
  - "3.8" 
  # nightly currently broken in travis
  #- "nightly"
env:
  - XMPP_SERVER=fake XMPP_SERVER_VERSION=1.0
  - XMPP_SERVER=ejabberd XMPP_SERVER_VERSION=16.01  # Ubuntu 16.04
  - XMPP_SERVER=ejabberd XMPP_SERVER_VERSION=16.09  # Debian Stretch
  - XMPP_SERVER=ejabberd XMPP_SERVER_VERSION=17.08  # Ubuntu 16.04 - apt.jabber.at
  - XMPP_SERVER=ejabberd XMPP_SERVER_VERSION=18.01  # Ubuntu 18.04
  - XMPP_SERVER=ejabberd XMPP_SERVER_VERSION=18.03
  - XMPP_SERVER=ejabberd XMPP_SERVER_VERSION=18.04
  - XMPP_SERVER=ejabberd XMPP_SERVER_VERSION=18.06
  - XMPP_SERVER=ejabberd XMPP_SERVER_VERSION=18.09
install:
  - pip install -U pip setuptools
  - pip install -r requirements.txt -r requirements-dev.txt
script:
  - ./test.py code-quality
  - python setup.py test
  - ./test.py test-server $XMPP_SERVER $XMPP_SERVER_VERSION
