sudo: required
services:
  - docker
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  # Python 3.7 is not yet supported by travis
  #- "3.7" 
  - "nightly"
env:
  - XMPP_SERVER=fake XMPP_SERVER_VERSION=1.0
  - XMPP_SERVER=ejabberd XMPP_SERVER_VERSION=14.07  # Debian Jessie
  - XMPP_SERVER=ejabberd XMPP_SERVER_VERSION=15.07  # Ubuntu 14.04 - apt.jabber.at
  - XMPP_SERVER=ejabberd XMPP_SERVER_VERSION=16.01  # Ubuntu 16.04
  - XMPP_SERVER=ejabberd XMPP_SERVER_VERSION=16.09  # Debian Stretch
  - XMPP_SERVER=ejabberd XMPP_SERVER_VERSION=17.04  # Debian Jessie - apt.jabber.at
  - XMPP_SERVER=ejabberd XMPP_SERVER_VERSION=17.08  # Ubuntu 16.04 - apt.jabber.at
  - XMPP_SERVER=ejabberd XMPP_SERVER_VERSION=18.01  # Ubuntu 18.04
  - XMPP_SERVER=ejabberd XMPP_SERVER_VERSION=18.03
  - XMPP_SERVER=ejabberd XMPP_SERVER_VERSION=18.04
  - XMPP_SERVER=ejabberd XMPP_SERVER_VERSION=18.06
  - XMPP_SERVER=ejabberd XMPP_SERVER_VERSION=18.09
install:
  - pip install -U pip setuptools
  - pip install -r requirements.txt -r requirements-dev.txt
script:
  - fab check
  - python setup.py test
  - fab test_server:$XMPP_SERVER,version=$XMPP_SERVER_VERSION
matrix:
  exclude:
    # 14.07 is very old, if someone uses that, most likely not with new python versions
    - env: XMPP_SERVER=ejabberd XMPP_SERVER_VERSION=14.07
      python: "3.5"
      python: "3.6"
      python: "nightly"
    # 15.07 is very old, if someone uses that, most likely not with new python versions
    - env: XMPP_SERVER=ejabberd XMPP_SERVER_VERSION=15.07
      python: "3.5"
      python: "3.6"
      python: "nightly"
