language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
install:
  - pip install -U pip setuptools
  - pip install -r requirements.txt -r requirements-dev.txt
script:
  - fab test_backend:xmpp_backends.dummy.DummyBackend,example.com
  - fab test_backend:xmpp_backends.django.fake_xmpp.backend.FakeXMPPBackend,example.com
stages:
  - check
  - test
jobs:
  - stage: check
    script:
        - fab check
        - python setup.py test
