sudo: required
services:
  - docker
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
env:
  - XMPP_SERVER=fake XMPP_SERVER_VERSION=1.0
  - XMPP_SERVER=ejabberd XMPP_SERVER_VERSION=14.07
  - XMPP_SERVER=ejabberd XMPP_SERVER_VERSION=16.01
  - XMPP_SERVER=ejabberd XMPP_SERVER_VERSION=16.09
  - XMPP_SERVER=ejabberd XMPP_SERVER_VERSION=17.04
  - XMPP_SERVER=ejabberd XMPP_SERVER_VERSION=17.07
  - XMPP_SERVER=ejabberd XMPP_SERVER_VERSION=18.01
  - XMPP_SERVER=ejabberd XMPP_SERVER_VERSION=18.03
install:
  - pip install -U pip setuptools
  - pip install -r requirements.txt -r requirements-dev.txt
script:
  - fab check
  - python setup.py test
  - fab test_server:$XMPP_SERVER,version=$XMPP_SERVER_VERSION
