xmpp_backends.dummy.DummyBackend:
    SERVER: fake
    DJANGO_SETUP: true
    ENVIRONMENT:
        DJANGO_SETTINGS_MODULE: tests.django_settings
    KWARGS:
        domains:
            - example.com
            - example.net
            - example.org

xmpp_backends.django.fake_xmpp.backend.FakeXMPPBackend:
    SERVER: fake
    DJANGO_SETUP: true
    DJANGO_MIGRATE: true
    PYTHONPATH: django_dev_project
    ENVIRONMENT:
        DJANGO_SETTINGS_MODULE: django_dev_project.fab_settings
    KWARGS:
        domains:
            - example.com
            - example.net
            - example.org

xmpp_backends.ejabberd_rest.EjabberdRestBackend:
  SERVER: ejabberd
  SERVER_MIN_VERSION: "16.02"
  DOCKER:
    container: mathiasertl/ejabberd
    ports: [5222, 5223, 5269, 5280]
  BEFORE_TEST:
    - sleep 5  # ejabberd takes a few seconds to start
    - docker exec %(DOCKER_CONTAINER)s /usr/sbin/ejabberdctl register api example.com secret
  EXPECTED_USERS:
    - api
  KWARGS:
    user: api@example.com
    password: secret

xmpp_backends.ejabberd_xmlrpc.EjabberdXMLRPCBackend:
  SERVER: ejabberd
  DOCKER:
    container: mathiasertl/ejabberd
    ports: [5222, 5223, 5269, 4560]
  BEFORE_TEST:
    - sleep 5  # ejabberd takes a few seconds to start
    - docker exec %(DOCKER_CONTAINER)s /usr/sbin/ejabberdctl register api example.com secret
  EXPECTED_USERS:
    - api
  KWARGS:
    user: api
    password: secret
    server: example.com
  VERSION_OVERRIDES:
    "14.07":
      KWARGS: {}

xmpp_backends.ejabberdctl.EjabberdctlBackend:
  SERVER: ejabberd
  DOCKER:
    container: mathiasertl/ejabberd
  BEFORE_TEST:
    - sleep 5  # ejabberd takes a few seconds to start
  KWARGS:
    path: [docker, exec, xmpp-backends-docker, /usr/sbin/ejabberdctl]

